steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--tag=${_GCP_REGION}-docker.pkg.dev/${_GCP_PROJECT_ID}/${_AR_REPO_NAME}/tswiqon-agent:latest'
  - '.' # Build context is core-backend/tswiqon/
  id: 'Build tswiqon_agent'
images:
- '${_GCP_REGION}-docker.pkg.dev/${_GCP_PROJECT_ID}/${_AR_REPO_NAME}/tswiqon-agent:latest'
substitutions:
  _GCP_REGION: 'europe-west3'
  _GCP_PROJECT_ID: 'awanon-ai-system'
  _AR_REPO_NAME: 'awanon-images'
options:
  machineType: 'E2_HIGHCPU_8' # For memory/CPU intensive pip install & FAISS build
